# Generated by Django 3.2.11 on 2022-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram URL', null=True),
        ),
    ]
