# Generated by Django 3.2.11 on 2022-02-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
            ],
        ),
    ]
